### ISSUE TITLE
Add features: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [sa-phystech/program_2020_zhuravlev#1]
[In task 3](https://github.com/sa-phystech/program_2020_zhuravlev/tree/master/lab3)

1. Add drawing unbind object. Now you draw grouped objects in a loop with increased size, change it to an arbitrary size for every object in your pic.
2. Animate clouds.
3. Add feature multiple types of roofs and windows.

**Comment by sa-phystech** [comment]
Добавлены анимированные облака, два типа крыш и три типа окон. Теперь можно выбирать размер домов.

**Comment by sa-phystech** [comment]
Добавлен результат работы программы, по рисованию картинки №2.
